CREATE TABLE USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(45) NOT NULL,
    login VARCHAR(45) NOT NULL
);

CREATE TABLE REGISTRATION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lecture_id BIGINT NOT NULL,
    created TIMESTAMP
);

ALTER TABLE REGISTRATION
    ADD CONSTRAINT registration_user_id
    FOREIGN KEY (user_id) REFERENCES user(id)
