CREATE TABLE USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(45) NOT NULL,
    login VARCHAR(45) NOT NULL
);

CREATE TABLE REGISTRATION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lecture_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL
);

CREATE TABLE LECTURE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    starting TIMESTAMP NOT NULL,
    ending TIMESTAMP NOT NULL,
    max_amount_of_users INT NOT NULL
);

ALTER TABLE REGISTRATION
    ADD CONSTRAINT registration_user_id
    FOREIGN KEY (user_id) REFERENCES user(id);

ALTER TABLE REGISTRATION
    ADD CONSTRAINT registration_lecture_id
    FOREIGN KEY (lecture_id) REFERENCES lecture(id);
